/**
 * Config do painel /dadosquizz e da telemetria do quiz.
 * Altere a senha antes de divulgar a URL do painel.
 */
window.ANALYTICS_CONFIG = {
  namespace: "birraquizz-erkni",
  dashboardPassword: "birra2026",
  counterApiBase: "https://api.counterapi.dev/v1",
  /** Funil expandido (método completo) */
  funnelKeys: [
    { key: "visit", label: "Acessou o quiz" },
    { key: "start", label: "Clicou em começar" },
    { key: "q1", label: "Q1 (quebra-gelo)" },
    { key: "q2", label: "Q2" },
    { key: "q3", label: "Q3" },
    { key: "q4", label: "Q4" },
    { key: "q5", label: "Q5" },
    { key: "q6", label: "Q6" },
    { key: "m_ice", label: "Micro: recompensa" },
    { key: "q7", label: "Q7 (dor)" },
    { key: "q8", label: "Q8" },
    { key: "q9", label: "Q9" },
    { key: "q10", label: "Q10" },
    { key: "q11", label: "Q11" },
    { key: "q12", label: "Q12" },
    { key: "q13", label: "Q13" },
    { key: "q14", label: "Q14" },
    { key: "q15", label: "Q15" },
    { key: "q16", label: "Q16" },
    { key: "m_pain", label: "Micro: dor / notícia" },
    { key: "social_video", label: "Prova social (vídeo)" },
    { key: "q17", label: "Q17 (desejo)" },
    { key: "q18", label: "Q18" },
    { key: "q19", label: "Q19" },
    { key: "q20", label: "Q20" },
    { key: "q21", label: "Q21" },
    { key: "q22", label: "Q22" },
    { key: "q23", label: "Q23" },
    { key: "q24", label: "Q24" },
    { key: "m_desire", label: "Micro: desejo" },
    { key: "q25", label: "Q25 (ponte)" },
    { key: "q26", label: "Q26" },
    { key: "q27", label: "Q27" },
    { key: "q28", label: "Q28" },
    { key: "q29", label: "Q29" },
    { key: "q30", label: "Q30" },
    { key: "m_bridge", label: "Micro: ponte" },
    { key: "eval", label: "Diagnóstico (avaliação)" },
    { key: "capture", label: "Tela de captura" },
    { key: "lead_capture", label: "Lead capturado (form ok)" },
    { key: "loading", label: "Loading" },
    { key: "result", label: "Pitch / resultado" },
    { key: "cta_checkout", label: "Clique checkout" },
  ],
};
